PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fhir: <http://hl7.org/fhir/>

SELECT 
  ?patient 
  ?path
WHERE {
  {
    SELECT
    (SUBSTR(?pat, 9) AS ?pat_id)
    WHERE {
      ?con fhir:Condition.code [ fhir:CodeableConcept.text [ fhir:value "Osteroporose" ] ] .
      ?con fhir:Condition.subject [ fhir:Reference.reference [ fhir:value ?pat ] ] .
    }
  }
  ?patient fhir:Patient.identifier [ fhir:Identifier.value [ fhir:value ?pat_id ] ] .
  ?patient fhir:sampleName ?path .
}
