name: Change tests

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "12 3 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update && rustup component add rustfmt
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: rustup update && rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy
        working-directory: ./lib/oxsdatatypes
      - run: cargo clippy
        working-directory: ./lib/oxrdf
      - run: cargo clippy
        working-directory: ./lib/sparesults
      - run: cargo clippy
        working-directory: ./lib/spargebra
      - run: cargo clippy --all-targets --all-features

  clippy_msv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: rustup update && rustup override set 1.60.0 && rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --  -D warnings -D clippy::all
        working-directory: ./lib/oxsdatatypes
      - run: cargo clippy --  -D warnings -D clippy::all
        working-directory: ./lib/oxrdf
      - run: cargo clippy -- -D warnings -D clippy::all
        working-directory: ./lib/sparesults
      - run: cargo clippy -- -D warnings -D clippy::all
        working-directory: ./lib/spargebra
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
        working-directory: ./server

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-deny || true
      - run: cargo deny check

  semver_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-semver-checks || true
      - run: cargo semver-checks check-release --exclude oxrocksdb-sys --exclude oxigraph_js --exclude pyoxigraph --exclude oxigraph_testsuite --exclude oxigraph_server

  test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features
        env:
          RUST_BACKTRACE: 1

  address_sanitizer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: rustup update && rustup override set nightly
      - run: sudo apt install -y llvm
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --tests --target x86_64-unknown-linux-gnu --workspace --exclude pyoxigraph --exclude oxigraph_testsuite --exclude oxigraph_server
        env:
          RUST_BACKTRACE: 1
          RUSTFLAGS: -Z sanitizer=address

  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - run: Remove-Item -LiteralPath "C:\msys64\" -Force -Recurse
      - run: cargo test --all-features
        env:
          RUST_BACKTRACE: 1

  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --all-features
        working-directory: ./lib

  rustdoc_msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: rustup update && rustup override set 1.60.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --all-features
        working-directory: ./lib
        env:
          RUSTDOCFLAGS: -D warnings

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo install typos-cli || true
      - run: typos

  clang_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y clang-format
      - run: clang-format --Werror --dry-run oxrocksdb-sys/api/*

  fuzz_changes:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: rust
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: address
          storage-repo: https://${{ secrets.FULL_ACCESS_TOKEN }}@github.com/oxigraph/clusterfuzzlite-oxigraph.git
      - uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: code-change
          sanitizer: address
          minimize-crashes: true
          parallel-fuzzing: true
          storage-repo: https://${{ secrets.FULL_ACCESS_TOKEN }}@github.com/oxigraph/clusterfuzzlite-oxigraph.git

  fuzz_repo:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: rust
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: address
      - uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 3600
          mode: batch
          sanitizer: address
          minimize-crashes: true
          parallel-fuzzing: true
          storage-repo: https://${{ secrets.FULL_ACCESS_TOKEN }}@github.com/oxigraph/clusterfuzzlite-oxigraph.git
        continue-on-error: true
      - uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 3600
          mode: prune
          storage-repo: https://${{ secrets.FULL_ACCESS_TOKEN }}@github.com/oxigraph/clusterfuzzlite-oxigraph.git
        continue-on-error: true

  fuzz_coverage:
    if: github.event_name != 'pull_request'
    needs: fuzz_repo
    runs-on: ubuntu-latest
    steps:
      - uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: rust
          sanitizer: coverage
      - uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 3600
          mode: coverage
          sanitizer: coverage
          storage-repo: https://${{ secrets.FULL_ACCESS_TOKEN }}@github.com/oxigraph/clusterfuzzlite-oxigraph.git
