name: Change tests

on:
  pull_request:
    branches:
      - main
      - next
  schedule:
    - cron: "12 3 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust
        with:
          component: rustfmt
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/setup-rust
        with:
          version: 1.76.0
          component: clippy
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
        working-directory: ./lib/oxsdatatypes
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
        working-directory: ./lib/oxrdf
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
        working-directory: ./lib/oxrdfxml
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
        working-directory: ./lib/oxttl
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
        working-directory: ./lib/oxrdfio
      - run: cargo clippy --all-targets --features async-tokio -- -D warnings -D clippy::all
        working-directory: ./lib/oxrdfio
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
        working-directory: ./lib/sparesults
      - run: cargo clippy --all-targets --features async-tokio -- -D warnings -D clippy::all
        working-directory: ./lib/sparesults
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
        working-directory: ./lib/spargebra
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
        working-directory: ./lib/sparopt
      - run: cargo clippy --all-targets --no-default-features -- -D warnings -D clippy::all
        working-directory: ./lib/oxigraph
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
        working-directory: ./lib/oxigraph
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
        working-directory: ./python
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
        working-directory: ./cli
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
        working-directory: ./testsuite

  clippy_msv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/setup-rust
        with:
          version: 1.76.0
          target: wasm32-unknown-unknown
          component: clippy
      - run: cargo clippy --lib --tests --target wasm32-unknown-unknown -- -D warnings -D clippy::all
        working-directory: ./js

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@v2
        with: { tool: cargo-deny }
      - run: cargo deny check

  semver_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/setup-rust
      - uses: taiki-e/install-action@v2
        with: { tool: cargo-semver-checks }
      - uses: actions/cache@v3
        with:
          path: rocksdb
          key: ${{ runner.os }}-rocksdb-8.0.0
      - run: bash .github/workflows/install_rocksdb.sh
      - run: cargo semver-checks check-release --exclude oxrocksdb-sys --exclude oxigraph-js --exclude pyoxigraph --exclude oxigraph-testsuite --exclude oxigraph-cli

  test_linux_x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/setup-rust
      - run: cargo test

  test_linux_i686:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/setup-rust
        with:
          target: i686-unknown-linux-gnu
      - run: sudo apt-get update && sudo apt-get install -y g++-multilib
      - run: cargo test --target i686-unknown-linux-gnu --no-default-features --features http-client-rustls-native
        working-directory: ./lib/oxigraph

  test_linux_msv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Read MSRV from Cargo.toml
        id: metadata
        run: echo "rust-version=$(sed -ne 's/rust-version *= *\"\(.*\)\"/\1/p' Cargo.toml)" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/setup-rust
        with:
          version: ${{ steps.metadata.outputs.rust-version }}
      - run: rustup toolchain install nightly
      - run: rm Cargo.lock && cargo +nightly update -Z direct-minimal-versions && cargo update -p bumpalo --precise 3.14.0
      - run: cargo test

  test_linux_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/setup-rust
      - run: rm Cargo.lock && cargo update
      - run: cargo test

  test_linux_address_sanitizer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/setup-rust
        with:
          version: nightly
      - run: sudo apt-get update && sudo apt-get install -y llvm
      - run: cargo test --tests --target x86_64-unknown-linux-gnu --workspace --exclude pyoxigraph --exclude oxigraph-testsuite --exclude oxigraph-cli
        env:
          RUSTFLAGS: -Z sanitizer=address

  test_linux_dynamic_linking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/setup-rust
      - uses: actions/cache@v3
        with:
          path: rocksdb
          key: ${{ runner.os }}-rocksdb-8.0.0
      - run: bash .github/workflows/install_rocksdb.sh
      - run: cargo test --tests --features oxrocksdb-sys/pkg-config

  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/setup-rust
      - run: Remove-Item -LiteralPath "C:\msys64\" -Force -Recurse
      - run: cargo test

  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/setup-rust
        with:
          version: 1.76.0
      - run: cargo doc
        env:
          RUSTDOCFLAGS: -D warnings

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@v2
        with: { tool: typos-cli }
      - run: typos

  clang_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y clang-format
      - run: clang-format --Werror --dry-run oxrocksdb-sys/api/*

  fuzz_changes:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: rust
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: address
          storage-repo: https://${{ secrets.FULL_ACCESS_TOKEN }}@github.com/oxigraph/clusterfuzzlite-oxigraph.git
      - uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 900
          mode: code-change
          sanitizer: address
          minimize-crashes: true
          parallel-fuzzing: true
          storage-repo: https://${{ secrets.FULL_ACCESS_TOKEN }}@github.com/oxigraph/clusterfuzzlite-oxigraph.git

  fuzz_repo:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: rust
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: address
      - uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 7200
          mode: batch
          sanitizer: address
          minimize-crashes: true
          parallel-fuzzing: true
          storage-repo: https://${{ secrets.FULL_ACCESS_TOKEN }}@github.com/oxigraph/clusterfuzzlite-oxigraph.git
        continue-on-error: true
      - uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 3600
          mode: prune
          storage-repo: https://${{ secrets.FULL_ACCESS_TOKEN }}@github.com/oxigraph/clusterfuzzlite-oxigraph.git
        continue-on-error: true

  fuzz_coverage:
    if: github.event_name != 'pull_request'
    needs: fuzz_repo
    runs-on: ubuntu-latest
    steps:
      - uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: rust
          sanitizer: coverage
      - uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 3600
          mode: coverage
          sanitizer: coverage
          storage-repo: https://${{ secrets.FULL_ACCESS_TOKEN }}@github.com/oxigraph/clusterfuzzlite-oxigraph.git
